name: Build AutoX APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jre

      - name: Unzip APK
        run: |
          mkdir apk
          unzip template/Ai华医.apk -d apk

      - name: Replace Project Files
        run: |
          cp main.js apk/assets/project/
          cp huayi.js apk/assets/project/
          cp project.json apk/assets/project/

          rm -rf apk/assets/project/res
          cp -r res apk/assets/project/

      - name: Repack APK
        run: |
          cd apk
          zip -r ../Ai华医_unsigned.apk .

      - name: Download Signer
        run: |
          wget -O signer.jar \
          https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar

      - name: Sign APK
        run: |
          java -jar signer.jar --apks Ai华医_unsigned.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ai华医
          path: "*aligned-debugSigned.apk"